// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_tlew1219.Models;

namespace Mission6_tlew1219.Migrations
{
    [DbContext(typeof(DateApplicationContext))]
    [Migration("20230221174355_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6_tlew1219.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("AppliationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppliationID");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            AppliationID = 1,
                            CategoryID = 1,
                            Director = "Martin Scorcese",
                            Edited = true,
                            LentTo = "",
                            Notes = "Incredible",
                            Rating = "R",
                            Title = "The Departed",
                            Year = (ushort)2006
                        },
                        new
                        {
                            AppliationID = 2,
                            CategoryID = 2,
                            Director = "Kevin Lima, Chris Buck",
                            Edited = false,
                            LentTo = "",
                            Notes = "Thank you Phil Collins",
                            Rating = "G",
                            Title = "Tarzan",
                            Year = (ushort)1999
                        },
                        new
                        {
                            AppliationID = 3,
                            CategoryID = 3,
                            Director = "Christopher Nolan",
                            Edited = true,
                            LentTo = "",
                            Notes = "Mind blowing",
                            Rating = "R",
                            Title = "Memento",
                            Year = (ushort)2000
                        });
                });

            modelBuilder.Entity("Mission6_tlew1219.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Mystery"
                        });
                });

            modelBuilder.Entity("Mission6_tlew1219.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission6_tlew1219.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
